# Generated by Django 3.2.3 on 2021-05-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_newapp', '0002_auto_20210528_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_newapp.school'),
        ),
    ]
